//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTapASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KIEMTRA_ASPEntities : DbContext
    {
        public KIEMTRA_ASPEntities()
            : base("name=KIEMTRA_ASPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tinh> Tinh { get; set; }
        public virtual DbSet<ThanhVien> ThanhVien { get; set; }
    
        public virtual ObjectResult<ThanhVien_TimKiem_Result> ThanhVien_TimKiem(string maTV, string hoTen, string ngaySinh, string gioiTinh, string email, string diaChi, string maTinh)
        {
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh != null ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maTinhParameter = maTinh != null ?
                new ObjectParameter("MaTinh", maTinh) :
                new ObjectParameter("MaTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThanhVien_TimKiem_Result>("ThanhVien_TimKiem", maTVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, emailParameter, diaChiParameter, maTinhParameter);
        }
    
        public virtual ObjectResult<Tinh_TimKiem_Result> Tinh_TimKiem(string maTinh, string tenTinh)
        {
            var maTinhParameter = maTinh != null ?
                new ObjectParameter("MaTinh", maTinh) :
                new ObjectParameter("MaTinh", typeof(string));
    
            var tenTinhParameter = tenTinh != null ?
                new ObjectParameter("TenTinh", tenTinh) :
                new ObjectParameter("TenTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tinh_TimKiem_Result>("Tinh_TimKiem", maTinhParameter, tenTinhParameter);
        }
    }
}
